### ISSUE TITLE
Cases where a curator has requested a 'bulk uploader'

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#100]
This ticket can be used to document cases where a curator has requested a 'bulk uploader' option.

This option is currently not available in PHI-Canto but is something we have discussed in the past and may be implemented in the future. 

The PomBase team have a bulk upload method.

During a meeting yesterday with @JonMWilkes, Jon was asking whether we had a bulk upload option so that he could curate PMID:28742144 which contains data on the knockdown of ~160 protein kinases in T. brucei.

Currently the genes would all have to be entered manually.

**Comment by ValWood** [comment]
Bulk upload should be easy for:
Single species phenotypes.
Modifications.
Expression.
You can  copy our upload formats.
https://www.pombase.org/submit-data/bulk-annotation

You will need to define a format for pathogen -host interactions, but this would not be urgent as they tend to be low throughput.

**Comment by CuzickA** [comment]
Thanks @ValWood 

@JonMWilkes are the phenotypes for the ~160 protein kinases in T. brucei single species in vitro pathogen phenotypes or Pathogen host interaction phenotypes where the pathogen mutants have been tested in a host?

**Comment by JonMWilkes** [comment]
Hi,Thanks for the quick replies – I’m answering this directly rather than through git-hub as I’m on my way out to work. Briefly the knockdown is a ‘massively parallel’ RNAi using a mixed population of T.brucei with RNAi cassettes targeted against identified kinases from the T.brucei genome. either in culture or in a mouse infection. RNAi is induced by doxycycline – phenotype is defined by the prevalence of the RNAi cassette within the population – reduction or elimination defining loss of fitness. Possible increase in prevalence may represent a gain of fitness or function, but is more problematic to establish. There is no genotype associated with the host, hence no formal metagenotype as I understand it.

**Comment by ValWood** [comment]
It sounds like this needs to be modelled as a pathogen-host interaction because the observation is requires the capture of the host strain. So I think it would need to be done in  PHICanto to get it through in a timely manner because you would need to define  and implement an upload fo.rmat

Also because there will presumably be a range of  phenotypes associated with individual knockdowns. At PomBAse we would tend to import datasets of this size, but we do them in Canto sometimes if there are variations in the  phenotypes.
It does not take too long because the green list can be uploaded ina single batch, and then once you have the basic pathogen host interaction phenotype you can copy edit.

Note also that Kim made some improvements to speed up the responsiveness of  large sessions so @jseager7 should ensure that these changes are in PHI-Canto.

**Comment by jseager7** [comment]
I'm closing this since we haven't had any more requests for bulk uploads.
