### ISSUE TITLE
can we capture pangenome data?

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#12]
![image](https://user-images.githubusercontent.com/11753634/46860480-7010a780-ce08-11e8-9664-12b4de25ed0e.png)

Can we link an experimentally tested gene/genotype/phenotype in PHI-base to available pangenome information indicating whether it is a core or variable gene (across a wide range of strains within a species)?
Eg for Fusarium graminearum or Zymoseptoria

This would provide researchers with a lot of information eg looking within the core genes across multiple strains of a species for chemistry targets or within the variable genes for effector genes.

The Pangenome strains will all be essentially WT (natural variation). Phenotypes identified in the original PHI-base experimentally verified mutant genotype would be predictions of expected phenotype outcomes if the same genes were manipulated within these other strains -however, a phenotype could only be given if genotype was actually created, tested and published.

**How could we capture this information**
-in PHI-Canto? as an annotation extension?
  _present in pangenome as a 'core gene'
  present in pangenome as a 'variable gene'_
but this would also require a link to a Pubmed id or pangenome id (if these exist) to reference pangenome source

-display as tab on planned PHI5 gene summary page? (too labor intensive for us to maintain, we would want author to capture this)

-Knetminer? this may be a better place for this information as the pangenome strain phenotypes would be predicted and PHI-base only captures experimentally verified phenotypes.

**Comment by ValWood** [comment]
Since this specific information is on a gene rather than on an annotation basis, I don't think Canto is the right place to collect it.
It seems as though there should be some core resource (i.e extracted from orthology prediction output) .
You would need to decide how far the conservation needs to be to call a gene core, etc.

I don't think the author should capture this, it's a bioinformatics exercise....

Inferred annotation is currently done outside of canto although we hope to include it eventually. 
For fission yeast, we would only do this for GO. Inferred phenotypes would need to be done by a curator and, like GO would use appropriate evidence codes to indicate that the annotation was inferred via sequence similarity. This is a big project extension, so you would need to specifically describe this in the grant proposal.

Knetminer seems like it might be a good place to do this.

**Comment by CuzickA** [comment]
closing for now
