### ISSUE TITLE
PMID: 25627815 Fungicide efflux and the MgMFS1 transporter contribute to the multidrug resistance phenotype in Zymoseptoria tritici field isolates

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#123]
This publication will be curated by our new biocurator @jingluodatacurator.

Queries relating to the curation of this publication can all be recorded in this issue by adding comments below.

We will continue to use the Google Doc for general queries/comments on using PHI-Canto and the help documentation :-)

curation link https://canto.phi-base.org/curs/721915f9be394d8e

**Comment by jingluodatacurator** [comment]
Hi Alayne, when I typed in the key words of the publication in UniProt, three entries came up see images in my Google Doc (couldn't copy the images on here not sure why). 
Is the first entry the right one?

**Comment by jingluodatacurator** [comment]
As I understood, the specific mutation in this publication is in the MgMFS1 gene promoter. I have discussed this with MP and she questioned if this is still suitable for curation?

**Comment by CuzickA** [comment]
> Hi Alayne, when I typed in the key words of the publication in UniProt, three entries came up see images in my Google Doc (couldn't copy the images on here not sure why). Is the first entry the right one?

Hi @jingluodatacurator, Sometimes it can be a bit tricky to find the correct UniProt id. Please could you provide me with the search details you entered in UniProt?

When I search using the GenBank accession id from the methods section of the paper DQ661911


![image](https://github.com/PHI-base/curation/assets/11753634/a5532cb3-7819-43af-bd42-db449426e607)

I get this UniProt entry

![image](https://github.com/PHI-base/curation/assets/11753634/6b79fc66-5390-4049-b3b8-1ca6aea4dab0)

I would suggest using this entry '[A4ZGP3](https://www.uniprot.org/uniprotkb/A4ZGP3/entry)', even though it comes from the unreviewed section of UniProt it is at least from one of the two reference proteomes strain IPO323. 
![image](https://github.com/PHI-base/curation/assets/11753634/fa1c3444-02f3-4296-8acd-765890f80d36)

**Comment by CuzickA** [comment]
> As I understood, the specific mutation in this publication is in the MgMFS1 gene promoter. I have discussed this with MP and she questioned if this is still suitable for curation?

I think it is possible to create a genotype indicating an alteration in the promoter but I don't think I have any examples of this yet.

When I skim read this paper to see if suitable for publication I noted that Fig 6 and 7 could probably be curated. These expts are testing MFS1 mutants with a 44bp deletion for alterations to growth on different chemistries.

I don't think we would be curating the 519bp insertion into the MFS1 promoter as this is found in natural variant strains rather than being a lab-engineered alteration. 
![image](https://github.com/PHI-base/curation/assets/11753634/2c1b9f37-06c4-47a0-88ae-bb3ad485bc59)

**Comment by jingluodatacurator** [comment]
AC: Hi @jingluodatacurator, Sometimes it can be a bit tricky to find the correct UniProt id. Please could you provide me with the search details you entered in UniProt?

Hi @CuzickA, the search details I put into UniProtKB were the key words of the literature title: MgMFS1 transporter, Multidrug resistance, Zymoseptoria tritici. I have discussed this with MP and she advised to put in the gene name and the species name as a rule of thumb?

**Comment by CuzickA** [comment]
`I have discussed this with MP and she advised to put in the gene name and the species name as a rule of thumb?`

Yes, this is correct

**Comment by CuzickA** [comment]
Tagging @jingluodatacurator

**Comment by jingluodatacurator** [comment]
Curation completed pending review.
Tagging @CuzickA

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, before I start checking this older curation session, please could you

1) email me your highlighted PDF
2) add a short summary of the expt to this GitHub, including how you found the UniProt ids etc
3) double check the annotations with your new additional curation knowledge and personal curation checklist
4) Please let me know when you've done the above and then I'll check the session. Thanks

**Comment by jingluodatacurator** [comment]
Summary of expt.:

(MgMFS1 gene disruption in MDR6 shows its involvement in the MDR6 phenotype)
Since MgMFS1 was strongly overexpressed in all tested MDR strains, we decided to analyse its role in the MDR phenotype by a gene replacement strategy. We attempted to build a replacement construct with the selection marker inserted between flanking regions upstream and downstream of the MgMFS1 gene. However, due to strong sequence polymorphisms of the MgMFS1 3′ region in the MDR6 and MDR7 strains, we were unable to amplify either of the flanking regions (data not shown). We constructed a replacement cassette instead, carrying the hygromycin resistance marker between the second intron and the third exon of MgMFS1 leading to a 44 bp deletion in the gene (Fig. 6A). Both MDR strains were transformed via Agrobacterium tumefaciens with the disruption construct, but hygromycin-resistant transformants were obtained only from the MDR6 strain. After their isolation, we tested 69 transformants for their sensitivity to tolnaftate. A total of 26 transformants were unable to grow on tolnaftate at 1 mg l−1, whereas the parental MDR6 strain grew (Fig. 6C)

We verified the MgMFS1 disruption event by PCR on six tolnaftate-sensitive transformants and two tolnaftate-resistant transformants (Fig. 6B). The PCR with the primer-pair QC2_FW and QC2_RV showed that all six tolnaftate-sensitive transformants (n° 10, 12, 15, 16, 22, 25) had integrated the disruption construct at the target locus, but neither of the tolnaftate-resistant transformants (n° 30, 60). We further confirmed that the MgMFS1 disruption event had occurred without additional ectopic integration of the construct for the transformants 10, 12, 15 and 16 by Southern blot (Fig. S1). These four transformants were used for all further analyses and hereafter referred to as mfs1Δ strains.

We tested the sensitivity of the mfs1Δ mutants to fungicides having different modes of action in comparison with the parental MDR6 strain and with the sensitive reference strain IPO323. Figure 7 displays the results of growth tests performed on solid media inoculated with successive 10-fold culture dilutions. This analysis revealed that the disruption of MgMFS1 in the MDR6 strain abolishes resistance to the squalene epoxidase inhibitors tolnaftate and terbinafine to levels similar or below that of the sensitive strain. Similarly, no growth was observed for the mfs1Δ mutants on the SDHI boscalid and bixafen, comparable with the sensitive control.

To further precise the sensitivity of the mfs1Δ mutants on some compounds, we measured the effect of tolnaftate, epoxiconazole and boscalid at different concentrations on germ-tube elongation and calculated the corresponding EC50 values (fungicide concentration inhibiting germ-tube elongation by 50%). The values shown in Fig. 7B refine the results from spot tests.

Overall, the disruption of MgMFS1 in the MDR6 strain reduced its resistance levels to three compounds 25-fold,
meaning that the mfs1Δ mutants were still 10 times less sensitive to the DMI epoxiconazole as compared with the
sensitive IPO323, which is likely due to the CYP51 genotype carried by the MDR6 recipient isolate.

**Comment by jingluodatacurator** [comment]
Uniprot ID: author has provided GenBank accession number DQ661911.1, therefore DQ661911 was used to locate the ID A4ZGP3.
Strains: IPO323 was the reference strain. MDR6 was the parent resistant strain used for transformation.

**Comment by jingluodatacurator** [comment]
Genotype creation:

mfs1Δ mutants have been curated for tolnaftate, epoxiconazole and boscalid for their more resistant phenotype.

**Comment by jingluodatacurator** [comment]
Curation completed pending review by @CuzickA thanks:

https://canto.phi-base.org/curs/721915f9be394d8e

**Comment by CuzickA** [comment]
AC notes as I understand info from paper

Field strains
IPO323 is a drug sensitive strain
MDR6 is a drug resistant strain (constitutive increased expression of (CYP51 and) MgMFS1)

Lab- engineered strains -for curation
(Fig 6 construct info and initial chemical testing)
Parent strain MDR6
MgMFS1 disruption cassette 44bp deletion in intron 3 in strain MDR6  (called mfs1delta by authors) -> shift in R to S for tolnaftate, epoxyconazole and boscalid (Figure 7)

**Comment by CuzickA** [comment]
Current annotations

![image](https://github.com/PHI-base/curation/assets/11753634/5a3dd5fe-2c2e-4b51-966c-fb091fdff82c)

**Comment by CuzickA** [comment]
The annotations mostly look good

Just to note the genotype could have been 'disruption' but as authors use 'Mfs1delta' it is probably best to continue using 'deletion' genotype. So this is fine to leave as is.

Hi @jingluodatacurator, the strain 'IPO323' used in the genotype here is incorrect. This should be 'MDR6'. It was the MDR6 R strain that had Mfs1 deleted which resulted in S to chemicals. I think IPO323 was just used as a S control in the assays.

I have changed this and now annotations look like this

![image](https://github.com/PHI-base/curation/assets/11753634/6bbe7c91-81fb-42a7-886b-7c95841a0506)

**Comment by CuzickA** [comment]
I have added new strain 2cc9fe0

**Comment by CuzickA** [comment]
AE alteration in archetype is N/A as NTSR.

**Comment by CuzickA** [comment]
I added a GO MF annotation

![image](https://github.com/PHI-base/curation/assets/11753634/ad1dadac-e81a-418b-9f15-29f25031e448)

**Comment by CuzickA** [comment]
> AC notes as I understand info from paper
> 
> Field strains 
IPO323 is a drug sensitive strain 
MDR6 is a drug resistant strain (constitutive increased expression of (CYP51 and) MgMFS1)
> 
> Lab- engineered strains -for curation 
(Fig 6 construct info and initial chemical testing) 
Parent strain MDR6 MgMFS1 disruption cassette 44bp deletion in intron 3 in strain MDR6 (called mfs1delta by authors) -> shift in R to S for tolnaftate, epoxyconazole and boscalid (Figure 7)

Hi @jingluodatacurator, sometimes it's good to make summary notes like these about how you understand what the authors have done, in addition to copying chunks of text from the paper as done above. It makes it easier to check whether the curator has fully understood the expt and if not to see where the difficulty is.

**Comment by CuzickA** [comment]
> Genotype creation:
> 
> mfs1Δ mutants have been curated for tolnaftate, epoxiconazole and boscalid for their more resistant phenotype.

I think this should say 'sensitive'.

**Comment by CuzickA** [comment]
Session now complete and approved.

Closing ticket
