### ISSUE TITLE
create a help page describing how to trouble shoot if you can't locate the uniprot entries you require 

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#14]
I just spent almost 20 minutes tracking down UniProt entries for specific genes.
Arabidopsis was easy, but I could not locate the hyaloperonospora  arabidopsidis gene. 

Googling 
hyaloperonospora+arabidopsidis and UniPRot + 
hyaloperonospora+arabidopsidis and uniPpot
or Peronospora parasitica

I searched UniPROt but I still could not locate using the species name and ATR1

Then I found these IDs in the paper
Sequence data that were used in this paper can be found in the National Center for Biotechnology Information databases under the following accession numbers: ATR1-Emoy2 (gi61660946), ATR1-Maks9 (gi61660952), ATR1-Emco5 (gi61660954), ATR1-Cala2 (gi61660958), ATR1-Emwa1 (gi61660960), RPP1-WsB (gi3860164).
but could not locate at the NCBI using any of these gi-numbers

I found a structure, but this did not lead me to the uniprot ID
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3156156/pdf/pnas.201109791.pdf
https://www.rcsb.org/structure/3RMR
sequence

I eventually found it by getting a table of ALL 14,000 H. parasitica (https://www.uniprot.org/uniprot/?query=hyaloperonospora+arabidopsidis&sort=genes&desc=no
sorting on gene name, and was able to find it with the gene name
ATR1NdWsB
This seems like gene name + strain name and allele name?
If so let UniPRot know  (these could be synonym but not be primary names? do you agree?)

I was only able to locate this by this method *because* I knew the name began with “A” and it would  not be to many to scroll through. There does not appear to be any filtering  or pattern match search available from this point, at least I could not easily see any other way.

There will be lots of issues like this , so here I suggest you create a flow chart of the order to try things, and what to try next if a specific action fails to slot into your documentation
https://curation.pombase.org/pombe/docs/index

eg
Dos the paper supply accession numbers?
if Uniprot -> proceed to https://www.uniprot.org/ to confirm
If ncbi -> https://www.google.com/search?q=NCBI retrieve entry 
  (Y)  Find xref to uniPRot in NCBI entry (describe how this is quite convoluted) Proceed to  to https://www.uniprot.org/ to validate and search on organism and gene name    )-> 
  (N) Proceed to  to https://www.uniprot.org/ to validate and search on organism and gene name 
       (Y) confirm
       (N) what to try next…

I suggest you draw up a basic version and we can refine over time  with tips as we encounter other oddities

(note we might need to modularise the documentation a bit going forwards)

**Comment by ValWood** [comment]
actions
- [ ] create flow chart for trouble shooting if a gene can't be located
- [ ]  report ATR1NdWsB issue to UniProt (especially in case this is standard practice)

**Comment by CuzickA** [comment]
Thanks for your post above @ValWood. It is really useful to document the problems. I think we may have some notes on this in the past when we looked at ATR1-RPP1 examples. I will try to dig them out.

From a quick look-see I have noticed that UniProt are using the wrong pathogen species (and NCBI taxon id)!!. Hyaloperonospora parasitica Taxonomy ID: 123356
search 'atr1 hyaloperonospora' gives
![image](https://user-images.githubusercontent.com/11753634/48483913-a462f380-e80c-11e8-99cc-540bf6a48141.png)
clicking on organism link gives
![image](https://user-images.githubusercontent.com/11753634/48483940-b5136980-e80c-11e8-832b-12b3a247344e.png)


It should be 
Hyaloperonospora arabidopsidis Taxonomy ID: 272952

**Comment by CuzickA** [comment]
I have found my notes on the ATR1 multiple UniProts. Click on the UniProt Id, then on the sequence id under 'sequence databases' to find the strain information.

Q4VKJ6 5 ENA sequence ids strains Emoy2 (x3 ids), Hiks1 and Waco5
Q4VKJ2 strain Noks1
Q4VKJ0 strain Emwa1
Q4VKJ1 strain Cala2
Q4VKJ3 strain Emco5
Q4VKJ4 strain maks9

Emoy2 is the reference strain but there does not appear to be a UniProt id specific to just this strain?

Would a PHI-canto user need to record the strain specific UniProt ids (part of a bigger conversation on reference/experimental strains).

**Comment by ValWood** [comment]
> Would a PHI-canto user need to record the strain specific UniProt ids (part of a bigger conversation on reference/experimental strains).

I don't think so. We are really only using this to check that we are referring to the correct gene 
(ATR1). It doesn't matter that uniProt use this entry for multiple strains. It's not clear to me why they teat some strains one way and merge into a single reference entry and other strains are treated as independent entries. We should ask about this.
Maybe the sequences are merged because they are identical? I see no variations reported so  this could be the case. It would  be useful to find this out.

**Comment by CuzickA** [comment]
I will email UniProt next week.

**Comment by CuzickA** [comment]
Email sent to UniProt today following up Hpa atr1 queries. 

Still to think about is the Arabidopsis RPP1 UniProt id. 
Do we use 
F4J339 Swiss-Prot reviewed entry from Col-0 reference genome

or UniProt strain specific ids for RPP1 described in the paper RPP1-NdA and RPP1-WsB
D9IW02 NdA unreviewed TrEMBL
Q9ZSN5 WsB unreviewed TrEMBL

Note: we do not know whether Col-0 RPP1 recognise atr1 and triggers ETI? 
RPP1 in Ws is a gene cluster RPP1-WsA, RPP1-WsA and RPP1-WsC. How to these correspond to F4J339 Swiss-Prot reviewed entry from Col-0 reference genome?

**Comment by CuzickA** [comment]
Text drafted for this in the 'Getting started' Help documentation (see below)

Closing this ticket for now.

Finding genes in UniProtKB
PHI-Canto uses UniProt Knowledgebase (UniProtKB) gene accession numbers to disambiguate genes/proteins. This is to ensure that we are talking about the correct gene product – especially as the same names are sometimes used for different proteins – and to standardize entries, because not all strains are in UniProt.
Identify the reference proteome (we use the designated reference proteome to integrate different strain information at the gene level in PHI-base). In PHI-Canto you will be able to specify the strain you used.
Look up the reference proteome for your organism using the species name (https://www.uniprot.org/help/reference_proteome).
If there is no reference proteome use the strain studied.
Identify the gene of interest in the reference proteome
Start from the UniProt homepage, then perform any of the following steps:
Search for the author assigned gene name/primary name (e.g. Tri5) or synonyms, plus species name (e.g Fusarium graminearum).
OR
If the gene does not have a ‘given name’ but a locus ID is provided, search using the locus_id (e.g. FGRRES_03537) plus species name (e.g. Fusarium graminearum). If the entry identifier used is not the reference strain, copy the protein sequence and go to the BLAST step below.
OR
Search on a protein description (e.g. Trichodiene synthase)
OR
Obtain the protein sequence for your gene of interest and BLAST against UniprotKB (https://www.uniprot.org/blast/) with your protein sequence.
Note: If there are multiple entries for your gene product from the reference strain, please select the ‘Reviewed entry’. Use the left hand filter for ‘Reviewed entries’.
							OR
If the gene cannot be located in UniProt, contact the authors, UniProt, or PHI-base for help locating the canonical database entry.
Add the entry into PHI-Canto. Once the entry of interest is located, select the entry accession number (also called ‘Entry’) from column 1 of the results table, and use this to retrieve the entry into PHI-Canto on the gene entry page. Be careful not to confuse the 'Entry' column with the 'Entry name' column. PHI-Canto uses the accession number to retrieve details (such as the gene name, gene product, and organism). If PHI-Canto is unable to find your entry, check for typos (e.g. 0 for O), ensure you are using the ‘entry’ not ‘entry name’, and check that your accession is from UniProtKB, not UniParc.
[add a screenshot of the results table with accession highlighted]
