### ISSUE TITLE
PMID14693557 FKS1 Mutations Responsible for Selective Resistance of Saccharomyces cerevisiae to the Novel 1,3--Glucan Synthase Inhibitor Arborcandin C

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#145]
Curated by @jingluodatacurator

https://canto.phi-base.org/curs/76d0683548c8db14

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/eb813f5f-82ef-47f3-a80f-99b789df7946)

I think that this should be two different genotypes and annotations. The publication indicates that these are single mutants rather than a double mutant.

![image](https://github.com/PHI-base/curation/assets/11753634/409b427f-5453-4cbc-89aa-523c92ed1511)

Changed annotations to 
![image](https://github.com/PHI-base/curation/assets/11753634/51c62fcf-c34b-4f37-bd90-a1a03b542975)

**Comment by CuzickA** [comment]
This session is just waiting for the PHI-ECO and PHIPO terms and then it will be ready for approval.

**Comment by jingluodatacurator** [comment]
Agreed and thanks to corrections @CuzickA .

**Comment by CuzickA** [comment]
PHI-ECO and PHIPO terms now added. Session approved. Closing ticket.

**Comment by CuzickA** [comment]
no archetype information found
