### ISSUE TITLE
PMID:26631591 The Y137H mutation of VvCYP51 gene confers the reduced sensitivity to tebuconazole in Villosiclava virens.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#191]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/4ed18899763f7b9f

**Comment by MPiovesana** [comment]
A mutant allele of the _CYP51_ gene of _Villosiclava virens_ was identified in a UV-irradiated mutant. The allele carries a point mutation which causes the Y137H amino acid substitution. The UV-irradiated mutant displayed increased resistance to tebuconazole compared to the parental strain (FJ4-1b), and a genetic transformation experiment confirmed the relationship between the mutant allele and chemical resistance.

**Comment by MPiovesana** [comment]
**Uniprot ID:** authors used two wild type strains (UV-8a and FJ4-1b) as reference in this study. They sequenced the _CYP51_ gene of both strains (which were identical), and deposited the sequence in GenBank (KJ004673). This accession number was used to retrieve the Uniprot ID of the protein (**X2GGV8**).

**Strain:** strain FJ4-1b was used as a recipient for the genetic transformation experiment.

**Comment by MPiovesana** [comment]
**Genotype creation:** as two experiments in this paper describe the generation of similar genotypes (one by UV irradiation and one by genetic transformation), I decided to curate the genetic transformation experiment only. 
A transformant allele was created to indicate the introduction of the mutant _CYP51_ allele from mutant UV10th (generated in the study by UV irradiation) into strain FJ4-1b:

**CYP51 transformant (UV10th-CYP51(Y137H)) [Not assayed]**

The recipient strain was also transformed with the WT CYP51 allele derived from itself (not a complementation control experiment as there is no mention of deleting the endogenous WT gene; the resulting lines from this transformation correspond to overexpression lines of CYP51):

**CYP51+ [overexpression]**

The presence of the endogenous _CYP51_ gene (authors do not mention deletion or gene replacement, so it can be assumed that the endogenous copy is still present) was recorded in background.

**Comment by MPiovesana** [comment]
**Genotype annotation:** both genotypes display increased resistance to tebuconazole compared to the parental FJ4-1b strain. The _CYP51+_ overexpression lines also show reduced colony growth rate, while the difference between WT and the _CYP51_ transformant is not significant (Table 2). The opposite is true when comparing sporulation, with the mutant allele causing a decrease whilst the overexpression of the WT allele does not affect this parameter. Neither allele affects spore germination. The following PHIPO terms were used:

resistance to tebuconazole
decreased rate of hyphae formation
normal hyphal growth
normal number of asexual spores
decreased number of asexual spores
normal asexual spore germination frequency

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Villosiclava virens (anamorph: Ustilaginoidea virens) 
also see https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1159556

**Comment by CuzickA** [comment]
I don't think this is correct
![image](https://github.com/PHI-base/curation/assets/11753634/810d9c1c-292d-49de-9a3a-01d656d473ba)

![image](https://github.com/PHI-base/curation/assets/11753634/654d3d3a-99a6-4837-b991-fa96cc029f7d)

There is no comparison with the WT strain here so we can't tell if the overexpression line (white squares) is more or less R to the chemical

Text from results
'To investigate whether overexpression of the VvCYP51 gene was able to confer the reduced sensitivity
to tebuconazole, the expression of the gene was determined in 26 pB-Vv51wt transformants and in
parental isolate FJ4-1b. Different levels of relative expression ranging from 2.57 to 24.23 were observed
(Table 1). EC50 values of the 26 pB-Vv51wt transformants ranged between 0.11 and 0.32 μ g/ml and
resistance factors ranged between 2.52 and 7.71 (Table 1). According to linear regression analysis, no
correlation was observed between the VvCYP51 expression levels and tebuconazole sensitivity (Fig. 4).'

Text from discussion
'While previous studies associated overexpression of CYP51B with resistance to DMI fungicides, this
study showed that a single point mutation rather than overexpression was associated with the reduced
sensitivity.'

Text from abstract
'Transformants carrying the mutated gene were more resistant to tebuconazole
compared to control transformants lacking the mutation, but the expression of the VvCYP51 gene
was not significantly correlated with EC50 values.'

Therefore I am changing the annotation to
![image](https://github.com/PHI-base/curation/assets/11753634/16878805-5830-416f-a7fc-745656302d83)

**Comment by CuzickA** [comment]
I have also added in the genotype and annotations for the UV mutant.

And increased RNA level.

**Comment by CuzickA** [comment]
Also added AE alteration in archetype

**Comment by CuzickA** [comment]
Approved and closing ticket

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

Y137H; Cyp51 (Cyp51B); SEPTTR

Straight forward to find in Nichola's S file in Table S2, Question about Cyp51/Cyp51B

![image](https://github.com/PHI-base/curation/assets/11753634/c292bba9-4981-4aad-a2d1-8e75885bf252)
![image](https://github.com/PHI-base/curation/assets/11753634/461d0a12-4ce3-4383-86c8-264311362bb6)

**Questions for Nichola**
1) Which cyp51a or cyp51b paralogue, and naming convention, same question as https://github.com/PHI-base/curation/issues/172

AC: Cyp51B is correct

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
