### ISSUE TITLE
How to curate the disease association

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#49]
I am now wondering it makes more sense to curate disease assoiations directly to the gene as a "curation type" "disease association" ?

Otherwise we will need to decide which phenotype to place this on as an extension?

Parastagonospora nodorum | A9JX75_PHANO needs (wheat) Stagonospora nodorum blotch (SNB),

**Comment by CuzickA** [comment]
No disease name recorded in this session https://canto.phi-base.org/curs/f41d30e250b8f9b0 
https://github.com/PHI-base/curation/issues/19
as pathogen and host constructs heterologously expressed in tobacco. It would have been nice to record that Hpa causes Downy Mildew on Arabidopsis.

**Comment by CuzickA** [comment]
For https://github.com/PHI-base/curation/issues/54
![image](https://user-images.githubusercontent.com/11753634/84261471-b8b7c100-ab13-11ea-89fb-d9467c95850b.png)
It does not seem correct to use disease name when no disease is observed -this will be removed

![image](https://user-images.githubusercontent.com/11753634/84261705-249a2980-ab14-11ea-91f2-eedbba253476.png)
It would be incorrect to use rice blast here as the tested host is barley -disease name will be removed

![image](https://user-images.githubusercontent.com/11753634/84261792-514e4100-ab14-11ea-8e2d-cb2872da32d4.png)
This is ok, disease name 'rice blast' can be used as disease symptoms visible and host is rice

Therefore 'rice blast' only added to 1/9 metagenotype annotations in this session

**Comment by CuzickA** [comment]
Added disease AE to some annotations in https://github.com/PHI-base/curation/issues/23 where host necrosis was present and AE 'unaffected pathogenicity' was used. 
See also https://github.com/PHI-base/phido/issues/2 for disease name synonym query.

**Comment by CuzickA** [comment]
https://github.com/PHI-base/curation/issues/36
I have only added disease 'aspergillous' to metagenotypes containing human host (rather than mouse and moth) in this session (although extending to an RNA phenotype seems a bit odd)
![image](https://user-images.githubusercontent.com/11753634/84504463-e76c9d80-acb3-11ea-83d0-dfc547a3cef3.png)

**Comment by CuzickA** [comment]
https://github.com/PHI-base/curation/issues/65
![image](https://user-images.githubusercontent.com/11753634/84524000-20673b00-acd1-11ea-818f-742a70369a9a.png)
Correct metagenotype to add 'potato wart' but perhaps not correct tissue type as 'warts' damage the tubers and these assays were performed on leaves.

**Comment by CuzickA** [comment]
See also https://github.com/pombase/canto/issues/2206

**Comment by CuzickA** [comment]
Use new curation type for 'Disease name' instead of AE causes_disease (to be removed)
Annotate all WT compatible (susceptible) metagenotypes (natural hosts only eg NOT Fg on Arabidopsis)
All strain combinations
All WT genes 

Select WT metagenotype, annotate with PHIDO term, select tissue from BTO, added Figure information.

This new method resolves the issues mentioned above in ticket.

See new query about natural variant genotypes #95 

See also https://github.com/pombase/canto/issues/2416

Closing this ticket for now
