### ISSUE TITLE
PMID: 31012804  A Remorin from Nicotiana benthamiana Interacts with the Pseudomonas Type-III Effector Protein HopZ1a and is Phosphorylated by the Immune-Related Kinase PBS1.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#64]
https://canto.phi-base.org/curs/3bbadf66303fe3a6

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/protein/XP_016479648.1 (TN90?)

**Comment by ValWood** [comment]
I am not able to proceed with this because the exoeriments use:

We sought to use N. benthamiana for further
functional analysis of the HopZ1a–remorin interaction because
of its amenability to molecular and cell biology manipulations
(Goodin et al. 2008). A homology search identified a remorinlike protein with high similarity (90%) to NtRemorin encoded
by the N. benthamiana genome (Niben101Scf00735g05005.1),
tentatively dubbed NbRemorin (Supplementary Fig. S1). A

but this is not in  uniprot. It seems to only be in a scaffold assembl so the accessions are likely to be unstable.

Action: Contact the authors and ask if they can submit the nucleotide sequence to NCBI or EMBL. Then it will get into Uniprot/Trembl.

**Comment by ValWood** [comment]
I also need to locate 
Pseudomonas syringae HopZ1a which should be easy but wasn't...

**Comment by CuzickA** [comment]
please look at this one @ValWood

**Comment by ValWood** [comment]
I dropped the ball on this. I only just mailed the authors.
